######################################
## Dockerfile for local development ##
######################################
FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get dist-upgrade -y
WORKDIR /app

ENV HOME=/app
ENV DAEMON_HOME=/app
ENV DAEMON_NAME=sidechaind

RUN mkdir /app/config
RUN mkdir -p /app/cosmovisor/genesis/bin
RUN mkdir -p /app/cosmovisor/upgrades

# Copy the library into the container
COPY development/deployment/libwasmvm.x86_64.so /usr/local/lib/
RUN ldconfig

COPY development/build/sidechaind  /app/cosmovisor/genesis/bin/sidechaind
COPY development/testnet/node0 ./
COPY cosmovisor/cosmovisor /app/cosmovisor/

RUN chmod +x /app/cosmovisor/genesis/bin/sidechaind
RUN chown -R nobody:nogroup /app
USER nobody
EXPOSE 26657
EXPOSE 9090
EXPOSE 1317
CMD ./cosmovisor/cosmovisor start --api.enable --grpc.enable --api.swagger --rpc.laddr "tcp://0.0.0.0:26657" --api.address "tcp://0.0.0.0:1317" --grpc.address "0.0.0.0:9090" --home /app