######################################
## Dockerfile for local development ##
######################################
FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get dist-upgrade -y
WORKDIR /app

ENV HOME=/app
ENV DAEMON_HOME=/app
ENV DAEMON_NAME=sidechaind

RUN mkdir /app/config
RUN mkdir -p /app/cosmovisor/genesis/bin
RUN mkdir -p /app/cosmovisor/upgrades

COPY development/build/sidechaind /app/cosmovisor/genesis/bin/sidechaind
COPY development/testnet/node2 ./
COPY cosmovisor/cosmovisor /app/cosmovisor/

RUN chmod +x /app/cosmovisor/genesis/bin/sidechaind
RUN chown -R nobody:nogroup /app
USER nobody
EXPOSE 26656
CMD ./cosmovisor/cosmovisor start --home /app