// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: side/yield/callbacks.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DelegateCallback struct {
	HostChainId string `protobuf:"bytes,1,opt,name=host_chain_id,json=hostChainId,proto3" json:"host_chain_id,omitempty"`
}

func (m *DelegateCallback) Reset()         { *m = DelegateCallback{} }
func (m *DelegateCallback) String() string { return proto.CompactTextString(m) }
func (*DelegateCallback) ProtoMessage()    {}
func (*DelegateCallback) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e12e852abdffd40, []int{0}
}
func (m *DelegateCallback) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DelegateCallback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DelegateCallback.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DelegateCallback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegateCallback.Merge(m, src)
}
func (m *DelegateCallback) XXX_Size() int {
	return m.Size()
}
func (m *DelegateCallback) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegateCallback.DiscardUnknown(m)
}

var xxx_messageInfo_DelegateCallback proto.InternalMessageInfo

func (m *DelegateCallback) GetHostChainId() string {
	if m != nil {
		return m.HostChainId
	}
	return ""
}

type UndelegateCallback struct {
	HostChainId string `protobuf:"bytes,1,opt,name=host_chain_id,json=hostChainId,proto3" json:"host_chain_id,omitempty"`
}

func (m *UndelegateCallback) Reset()         { *m = UndelegateCallback{} }
func (m *UndelegateCallback) String() string { return proto.CompactTextString(m) }
func (*UndelegateCallback) ProtoMessage()    {}
func (*UndelegateCallback) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e12e852abdffd40, []int{1}
}
func (m *UndelegateCallback) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UndelegateCallback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UndelegateCallback.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UndelegateCallback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UndelegateCallback.Merge(m, src)
}
func (m *UndelegateCallback) XXX_Size() int {
	return m.Size()
}
func (m *UndelegateCallback) XXX_DiscardUnknown() {
	xxx_messageInfo_UndelegateCallback.DiscardUnknown(m)
}

var xxx_messageInfo_UndelegateCallback proto.InternalMessageInfo

func (m *UndelegateCallback) GetHostChainId() string {
	if m != nil {
		return m.HostChainId
	}
	return ""
}

type TransferCallback struct {
	DepositRecordId uint64 `protobuf:"varint,1,opt,name=deposit_record_id,json=depositRecordId,proto3" json:"deposit_record_id,omitempty"`
}

func (m *TransferCallback) Reset()         { *m = TransferCallback{} }
func (m *TransferCallback) String() string { return proto.CompactTextString(m) }
func (*TransferCallback) ProtoMessage()    {}
func (*TransferCallback) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e12e852abdffd40, []int{2}
}
func (m *TransferCallback) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TransferCallback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TransferCallback.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TransferCallback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferCallback.Merge(m, src)
}
func (m *TransferCallback) XXX_Size() int {
	return m.Size()
}
func (m *TransferCallback) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferCallback.DiscardUnknown(m)
}

var xxx_messageInfo_TransferCallback proto.InternalMessageInfo

func (m *TransferCallback) GetDepositRecordId() uint64 {
	if m != nil {
		return m.DepositRecordId
	}
	return 0
}

func init() {
	proto.RegisterType((*DelegateCallback)(nil), "side.yield.DelegateCallback")
	proto.RegisterType((*UndelegateCallback)(nil), "side.yield.UndelegateCallback")
	proto.RegisterType((*TransferCallback)(nil), "side.yield.TransferCallback")
}

func init() { proto.RegisterFile("side/yield/callbacks.proto", fileDescriptor_1e12e852abdffd40) }

var fileDescriptor_1e12e852abdffd40 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0xb1, 0x4a, 0xc4, 0x30,
	0x1c, 0xc6, 0x5b, 0x10, 0xc1, 0x88, 0x78, 0x16, 0x07, 0xed, 0x10, 0xa4, 0x93, 0xdc, 0xd0, 0x70,
	0x08, 0xe2, 0xe4, 0xe0, 0xdd, 0x72, 0x6b, 0xd1, 0xc5, 0xa5, 0xa4, 0xc9, 0xdf, 0x36, 0xd8, 0xeb,
	0xbf, 0x24, 0x51, 0xbc, 0xb7, 0xf0, 0xb1, 0x1c, 0x6f, 0x74, 0x94, 0xf6, 0x45, 0x24, 0x49, 0xf5,
	0x01, 0x6e, 0xcb, 0xf7, 0xfb, 0xe5, 0x23, 0xe4, 0x23, 0xa9, 0x51, 0x12, 0xd8, 0x56, 0x41, 0x2b,
	0x99, 0xe0, 0x6d, 0x5b, 0x71, 0xf1, 0x6a, 0xf2, 0x5e, 0xa3, 0xc5, 0x84, 0x38, 0x97, 0x7b, 0x97,
	0x9e, 0xd7, 0x58, 0xa3, 0xc7, 0xcc, 0x9d, 0xc2, 0x8d, 0xf4, 0x52, 0xa0, 0xd9, 0xa0, 0x29, 0x83,
	0x08, 0x61, 0x52, 0x34, 0x24, 0x56, 0x71, 0x03, 0xec, 0x7d, 0x51, 0x81, 0xe5, 0x0b, 0x26, 0x50,
	0x75, 0xc1, 0x67, 0xb7, 0x64, 0xb6, 0x82, 0x16, 0x6a, 0x6e, 0x61, 0x39, 0xbd, 0x9b, 0x64, 0xe4,
	0xa4, 0x41, 0x63, 0x4b, 0xd1, 0x70, 0xd5, 0x95, 0x4a, 0x5e, 0xc4, 0x57, 0xf1, 0xf5, 0x51, 0x71,
	0xec, 0xe0, 0xd2, 0xb1, 0xb5, 0xcc, 0xee, 0x48, 0xf2, 0xd4, 0xc9, 0x7d, 0x9a, 0xf7, 0x64, 0xf6,
	0xa8, 0x79, 0x67, 0x5e, 0x40, 0xff, 0xf7, 0xe6, 0xe4, 0x4c, 0x42, 0x8f, 0x46, 0xd9, 0x52, 0x83,
	0x40, 0x2d, 0xff, 0xba, 0x07, 0xc5, 0xe9, 0x24, 0x0a, 0xcf, 0xd7, 0xf2, 0x61, 0xf5, 0x35, 0xd0,
	0x78, 0x37, 0xd0, 0xf8, 0x67, 0xa0, 0xf1, 0xe7, 0x48, 0xa3, 0xdd, 0x48, 0xa3, 0xef, 0x91, 0x46,
	0xcf, 0xf3, 0x5a, 0xd9, 0xe6, 0xad, 0xca, 0x05, 0x6e, 0x98, 0xdb, 0xcc, 0xff, 0x50, 0x60, 0xeb,
	0x03, 0xfb, 0x98, 0xe6, 0xb5, 0xdb, 0x1e, 0x4c, 0x75, 0xe8, 0xe5, 0xcd, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x02, 0x39, 0xa7, 0x83, 0x79, 0x01, 0x00, 0x00,
}

func (m *DelegateCallback) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DelegateCallback) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DelegateCallback) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.HostChainId) > 0 {
		i -= len(m.HostChainId)
		copy(dAtA[i:], m.HostChainId)
		i = encodeVarintCallbacks(dAtA, i, uint64(len(m.HostChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UndelegateCallback) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UndelegateCallback) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UndelegateCallback) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.HostChainId) > 0 {
		i -= len(m.HostChainId)
		copy(dAtA[i:], m.HostChainId)
		i = encodeVarintCallbacks(dAtA, i, uint64(len(m.HostChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TransferCallback) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TransferCallback) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TransferCallback) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DepositRecordId != 0 {
		i = encodeVarintCallbacks(dAtA, i, uint64(m.DepositRecordId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintCallbacks(dAtA []byte, offset int, v uint64) int {
	offset -= sovCallbacks(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DelegateCallback) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.HostChainId)
	if l > 0 {
		n += 1 + l + sovCallbacks(uint64(l))
	}
	return n
}

func (m *UndelegateCallback) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.HostChainId)
	if l > 0 {
		n += 1 + l + sovCallbacks(uint64(l))
	}
	return n
}

func (m *TransferCallback) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DepositRecordId != 0 {
		n += 1 + sovCallbacks(uint64(m.DepositRecordId))
	}
	return n
}

func sovCallbacks(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCallbacks(x uint64) (n int) {
	return sovCallbacks(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DelegateCallback) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCallbacks
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DelegateCallback: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DelegateCallback: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCallbacks
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCallbacks
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCallbacks
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HostChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCallbacks(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCallbacks
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UndelegateCallback) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCallbacks
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UndelegateCallback: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UndelegateCallback: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCallbacks
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCallbacks
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCallbacks
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HostChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCallbacks(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCallbacks
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TransferCallback) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCallbacks
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TransferCallback: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TransferCallback: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositRecordId", wireType)
			}
			m.DepositRecordId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCallbacks
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DepositRecordId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCallbacks(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCallbacks
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCallbacks(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCallbacks
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCallbacks
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCallbacks
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCallbacks
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCallbacks
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCallbacks
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCallbacks        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCallbacks          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCallbacks = fmt.Errorf("proto: unexpected end of group")
)
